# Generated by Django 5.1.4 on 2026-08-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_program_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("REGISTRAR", "Registrar"),
                    ("DEPT_HEAD", "Department Head"),
                    ("VIEWER", "Viewer"),
                ],
                default="VIEWER",
                max_length=20,
            ),
        ),
    ]
