# Generated by Django 5.1.4 on 2026-08-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_managed_program_codes_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_course_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="managed_department_codes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
