# Generated by Django 5.1.4 on 2026-09-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_dept_course_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="disabled_conflict_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
