# Generated by Django 5.1.4 on 2026-04-11 03:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time')], max_length=20)),
                ('priority_level', models.PositiveSmallIntegerField(default=0)),
                ('max_load_units', models.DecimalField(decimal_places=1, default=24, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'faculty',
                'db_table': 'scheduling_faculty',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('availability_type', models.CharField(choices=[('AVAILABLE', 'Available'), ('PREFERRED', 'Preferred'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=15)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_availability', to='scheduling.academicperiod')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='scheduling.faculty')),
            ],
            options={
                'verbose_name_plural': 'faculty availability',
                'db_table': 'scheduling_faculty_availability',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LABORATORY', 'Laboratory'), ('COMPUTER_LAB', 'Computer Lab'), ('AVR', 'AVR'), ('OTHER', 'Other')], max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('building', models.CharField(blank=True, default='', max_length=100)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('sequence_number', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.tenant')),
            ],
            options={
                'db_table': 'scheduling_rooms',
                'ordering': ['building', 'floor', 'sequence_number', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_start_time', models.TimeField(default='07:00')),
                ('latest_end_time', models.TimeField(default='21:00')),
                ('time_slot_granularity_minutes', models.PositiveSmallIntegerField(default=30)),
                ('operating_days', models.JSONField(default=list)),
                ('break_periods', models.JSONField(blank=True, default=list)),
                ('weight_faculty_priority', models.PositiveSmallIntegerField(default=50)),
                ('weight_room_proximity', models.PositiveSmallIntegerField(default=50)),
                ('weight_time_gap_minimization', models.PositiveSmallIntegerField(default=30)),
                ('weight_load_distribution', models.PositiveSmallIntegerField(default=30)),
                ('academic_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='scheduling.academicperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_configs', to='core.tenant')),
            ],
            options={
                'db_table': 'scheduling_config',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('group_id', models.UUIDField(default=uuid.uuid4)),
                ('entry_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab')], default='LECTURE', max_length=10)),
                ('load_classification', models.CharField(choices=[('REGULAR', 'Regular'), ('OVERLOAD', 'Overload'), ('BUILT_IN', 'Built-In'), ('PART_TIME', 'Part-Time')], default='REGULAR', max_length=20)),
                ('class_size', models.PositiveSmallIntegerField(default=0)),
                ('faculty_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='scheduling.academicperiod')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='scheduling.course')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='scheduling.faculty')),
                ('linked_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='scheduling.scheduleentry')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='scheduling.room')),
                ('sections', models.ManyToManyField(blank=True, related_name='schedule_entries', to='scheduling.section')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='core.tenant')),
            ],
            options={
                'db_table': 'scheduling_entries',
                'ordering': ['day_of_week', 'time_start'],
                'indexes': [models.Index(fields=['tenant', 'academic_period', 'day_of_week', 'time_start', 'time_end'], name='scheduling__tenant__e9ff81_idx'), models.Index(fields=['tenant', 'academic_period', 'faculty'], name='scheduling__tenant__32e016_idx'), models.Index(fields=['tenant', 'academic_period', 'room'], name='scheduling__tenant__568492_idx'), models.Index(fields=['group_id'], name='scheduling__group_i_a49f9b_idx')],
            },
        ),
    ]
