# Generated by Django 5.1.4 on 2026-09-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_dept_course_codes"),
        ("scheduling", "0002_faculty_facultyavailability_room_scheduleconfig_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature", models.CharField(max_length=500)),
                ("conflict_type", models.CharField(max_length=20)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_dismissals",
                        to="scheduling.academicperiod",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflict_dismissals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_dismissals",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "scheduling_conflict_dismissals",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "academic_period", "signature"),
                        name="uniq_dismissal_signature",
                    )
                ],
            },
        ),
    ]
